//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetAndWin.PaymentService.Web.Controls {
    
    
    public partial class CreditCardBinRangeBatchStateTypeFilter {
        
        /// <summary>
        /// creditCardBinRangeBatchStateTypeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLabel creditCardBinRangeBatchStateTypeLabel;
        
        /// <summary>
        /// creditCardBinRangeBatchStateTypeCombo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.DropDownListView creditCardBinRangeBatchStateTypeCombo;
    }
}
