//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using BetAndWin.PaymentService.Web.Controls.PaymentFilters;

namespace BetAndWin.PaymentService.Web.Controls.CashManagement
{
    public partial class ElectronicBankStatementCommonFilter
    {
        protected MerchantFilter merchantFilter;
        protected BankAccountFilter bankAccountFilter;
        protected DateTimeFilter bankStatementDateFilter;
    }
}
