//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetAndWin.PaymentService.Web.Controls.CashManagement {
    
    
    public partial class ElectronicBankStatementDetails {
        
        /// <summary>
        /// bankStatementDetailLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLabel bankStatementDetailLabel;
        
        /// <summary>
        /// bankNameLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLabel bankNameLabel;
        
        /// <summary>
        /// bankNameLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal bankNameLiteral;
        
        /// <summary>
        /// accountNameLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLabel accountNameLabel;
        
        /// <summary>
        /// accountNameLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal accountNameLiteral;
        
        /// <summary>
        /// accountNumberLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLabel accountNumberLabel;
        
        /// <summary>
        /// accountNumberLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal accountNumberLiteral;
        
        /// <summary>
        /// viewClearTextAccountNumberButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLinkButton viewClearTextAccountNumberButton;
        
        /// <summary>
        /// bankStatementDateLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLabel bankStatementDateLabel;
        
        /// <summary>
        /// bankStatementDateLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal bankStatementDateLiteral;
        
        /// <summary>
        /// bankStatementNumberLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLabel bankStatementNumberLabel;
        
        /// <summary>
        /// bankStatementNumberLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal bankStatementNumberLiteral;
        
        /// <summary>
        /// currencyLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLabel currencyLabel;
        
        /// <summary>
        /// currencyLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal currencyLiteral;
        
        /// <summary>
        /// startingAccountBalanceLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLabel startingAccountBalanceLabel;
        
        /// <summary>
        /// startingAccountBalanceLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal startingAccountBalanceLiteral;
        
        /// <summary>
        /// creditsSumAmountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLabel creditsSumAmountLabel;
        
        /// <summary>
        /// creditsSumAmountLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal creditsSumAmountLiteral;
        
        /// <summary>
        /// debitsSumAmountLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLabel debitsSumAmountLabel;
        
        /// <summary>
        /// debitsSumAmountLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal debitsSumAmountLiteral;
        
        /// <summary>
        /// endingAccountBalanceLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLabel endingAccountBalanceLabel;
        
        /// <summary>
        /// endingAccountBalanceLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal endingAccountBalanceLiteral;
        
        /// <summary>
        /// closingAvailableBalanceLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Framework.Web.UI.LocalizableLabel closingAvailableBalanceLabel;
        
        /// <summary>
        /// closingAvailableBalanceLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal closingAvailableBalanceLiteral;
    }
}
